Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -53,11 +53,19 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Set the release version
+      - name: Set the release version from the tag
         shell: bash
-        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
+        run: |
+          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
+            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+          else
+            echo "Error: GITHUB_REF does not point to a tag." >&2
+            exit 1
+          fi
 
+      - name: Print release version
+        run: echo "Release version is $RELEASE_VERSION"
+        
       - name: Install Rust toolchain
         uses: actions-rs/toolchain@v1
         with:
